import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'john@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmn: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px x 829
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 20,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas slim shirt',
      slug: 'adidas-slim-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '3',
      name: 'Nike slim pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 2.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Adidas fit pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 1,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '5',
      name: 'Guchi fit pant',
      slug: 'guchi-fit-pant',
      category: 'Pants',
      image: '/images/p5.avif',
      price: 400,
      countInStock: 0,
      brand: 'Guchi',
      rating: 3,
      numReviews: 5,
      description: 'high quality product from guchi',
    },
  ],
};

export default data;
