export const states = {
  Nigeria: [
    "Abuja(fct)",
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
  ],
  SouthAfrican: [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "Northern Cape",
    "North West",
    "Western Cape",
  ],
};

export const banks = {
  Nigeria: [
    "Access Bank",
    "Zenith Bank",
    "GTBank",
    "First Bank of Nigeria",
    "UBA",
    "Union Bank",
    "Fidelity Bank",
    "FCMB",
    "Citibank Nigeria",
    "Ecobank",
    "Heritage Bank",
    "Keystone Bank",
    "Standbic IBTC",
    "Standard Chartered",
    "Sterling Bank",
    "Unity Bank",
    "Wema Bank",
  ],
  SouthAfrica: [
    " Absa Bank",
    " African Bank",
    " Bidvest Bank",
    " Capitec Bank",
    " Discovery Bank",
    " First National Bank",
    " Investec",
    " Nedbank",
    " Standard Bank",
    " Ubank",
    " TymeBank",
  ],
};

export const pudo = {
  "Eastern Cape": [
    "43 Air School",
    "Addo Brauhaus Paterson",
    "Amalinda Square",
    "Bathurst Butchery",
    "Beacon Bay Retail Park",
    "Bothas Garage",
    "Build It Bushmans",
    "Build It Engcobo",
    "Build It Maclear",
    "Build It Siyaavuma",
    "Caltex Alexandria",
    "Caltex Dewing Service Station",
    "Caltex Ntande",
    "Cest La Vie",
    "Coastal Arcade Kenton On Sea",
    "Die Windmeul Oyster Bay",
    "Engen Malabar",
    "Equionx Mall",
    "Flagstaff Square",
    "Foodzone Patensie",
    "Gently Worn",
    "Gillwell Taxi Retail Park",
    "Gonubie Mall",
    "Greenacres Shopping Centre",
    "Hill Street Supermarket",
    "Hozizon Mini Market",
    "Jeffreys Bay Surf Village",
    "Kidds Beach Retail Centre",
    "Kwikspar Colchester",
    "Madala Hardware",
    "Market Square Grahamstown",
    "Moffett Retail Park",
    "Mount Road Pharmacy",
    "Ngcwangubu Mega Save",
    "Nonesi Mall",
    "Noorsveld Farm",
    "OK Foods Golden Valley",
    "OK Minimark Cuyler Street",
    "OK Minimark Despatch",
    "Oviston General",
    "OVK Aliwal North",
    "OVK Barkly East",
    "OVK Burgersdorp",
    "OVK Cradock",
    "OVK Elliot",
    "OVK Hofmeyer",
    "OVK Jamestown",
    "OVK Lady Grey",
    "OVK Middleburg EC",
    "OVK Molteno",
    "OVK Steynsburg",
    "OVK Tarkastad",
    "OVK Willowmore",
    "Ozzies General Store",
    "Paradise Supermarket",
    "Pearston Post office",
    "Pick n Pay 4th Avenue",
    "Rosehill Mall",
    "Royal Joubertina",
    "Royal Krakeel",
    "Royal Louterwater",
    "Royal Misgund",
    "S&J Enterprises",
    "Sasol Abbotsford",
    "Sasol Cape Road",
    "Sasol Chiselhurst",
    "Sasol Fig Tree",
    "Sasol Mdantsane",
    "Sasol Motherwell",
    "Sasol Stanford Road",
    "Sasol Summerstrand",
    "Sasol Volkstud Motors",
    "Savenor Mooiplaas",
    "Saverite Willowmore",
    "SB Motors Somerest East",
    "Settlers Square",
    "Sibuyile Home and Hardware",
    "Spar Bedford",
    "Spar Cala",
    "Spar Cradock",
    "Spar Dagbreek",
    "Spar Indwe",
    "Spar Lady Frere",
    "Spar Ngqamakhwe",
    "Spar Swartkops",
    "Spar Ugie",
    "Spargs Spar Qumbu",
    "Spargs Superspar Butterworth",
    "Spargs Superspar Dutywa",
    "Spargs Superspar Libode",
    "Sterkspruit Plaza",
    "Strand Supermarket",
    "Summerstrand Village Shopping Centre",
    "Superspar Spargs Sprigg",
    "The Courier Guy Alice",
    "The Courier Guy Aliwal North",
    "The Courier Guy Arcadia",
    "The Courier Guy East London",
    "The Courier Guy East London Depot",
    "The Courier Guy Fort Beaufort",
    "The Courier Guy Gonubie",
    "The Courier Guy Graaff Reinet",
    "The Courier Guy Grahamstown",
    "The Courier Guy Jeffreys Bay",
    "The Courier Guy",
    "Middleburg (Eastern Cape)",
    "The Courier Guy Mthatha",
    "The Courier Guy Port Alfred",
    "The Courier Guy port Elizabeth",
    "The Courier Guy Port Elizabeth Kiosk",
    "The Courier Guy Queenstown",
    "The Courier Guy Stutterheim",
    "The Courier Guy Walmer",
    "The Mall King Williams Town",
    "The Village Inn",
    "Total Expressmart Kareedouw",
    "TWK Cedarville",
    "Uncle Freddies",
    "Universal Garage Dordrecht",
    "Vroutjie Se Koutjie",
    "Walker Drive Shopping Centre",
    "Ziyabuya Shopping Centr",
  ],
  "Free State": [
    "AECI Plant Health",
    "Allanridge Engineering",
    "Bloem Plaza",
    "Boxer Welkom",
    "BP Edenburg",
    "Build It Bethlehem",
    "Cooper Penny",
    "Craibs Kontantwinkel",
    "DA Motors Boshof",
    "De Nice Buthchery Deneysville",
    "Dihlabeng Mall",
    "Edenville Quest",
    "Elegant Fuel Thaba Nchu",
    "Elegant Fuel Welkom",
    "Ellas Algemene Handelaar",
    "Engen Truck Stop",
    "Gardenia Square",
    "Heilbron herald",
    "Hinterland Fuels Theunissen",
    "Horeb Supermarket & Butchery",
    "Jostas Corner Koppies",
    "Kairuz Midas",
    "Kgotso Build 4ways",
    "Kgotso Build Botshabelo",
    "Liplekker Supermark",
    "Maluti Superspar",
    "Mega Park Bloemfontein",
    "Middestad Mall",
    "OK Costas Supermarket",
    "OK Express Harrismith",
    "OK Foods Clocolan",
    "Foods Frankfort",
    "OK Minimark Gariep",
    "OVK Bethulie",
    "OVK Brandfort",
    "OVK Clocolan",
    "OVK Dewetsdorp",
    "OVK Fauresmith",
    "OVK Fouriesburg",
    "OVK Hobhouse",
    "OVK Ladybrand",
    "OVK Paul Roux",
    "OVK Reddersburg",
    "OVK Riet Rivier",
    "OVK Rosendal",
    "OVK Rouxville",
    "OVK Smithfield",
    "OVK Trompsburg",
    "OVK Tweespruit",
    "OVK Ventersburg",
    "OVK verteerdevlei",
    "OVK Zastron",
    "Petrusburg Vleismark",
    "Phutaditjhaba Maluti Cresent",
    "Pick n Pay Hoopstad",
    "Pick n Pay Odendaalsrus",
    "Pienk Huis Deli",
    "Puma Warden",
    "Riemland Country Stop",
    "Sakkies Motors",
    "Sasol Mapikela",
    "Sasol One RCC",
    "Sasol Parys",
    "Sasol Power Road",
    "Sasol Vaalpark",
    "Sasol Villiers",
    "Saverite Villiers",
    "Shell Senekal",
    "Shoprite Virginia (Orange Free State)",
    "Spar Parys",
    "Spar Reitz",
    "Spar Vrede",
    "Spar Wesselsbron",
    "The Courier Guy Bethlehem",
    "The Courier Guy Bloemfontein",
    "The Courier Guy Bloemfontein Depot",
    "The Courier Guy Bloemfontein Langenhoven Park",
    "The Courier Guy Bloemfontein Preller Mall",
    "The Courier Guy Botshabelo",
    "The Courier Guy Ficksburg",
    "The Courier Guy Frankfort",
    "The Courier Guy Harrismith",
    "The Courier Guy Kroonstad",
    "The Courier Guy Ladybrand",
    "The Courier Guy Sasolburg",
    "The Courier Guy Virginia (Orange Free State)",
    "The Courier Guy Welkom",
    "TNT Tool Hire",
    "Value Mart Bloemfontein",
    "Vredefort Meubels",
    "Waterbron Cash Store",
    "Winburg Mecca",
    "Windsor Slaghui",
  ],
  Gauteng: [
    "68 On Hobart",
    "Adventure Zone Cullinan",
    "Aero Centre",
    "Alberton City",
    "Alberton Crossing",
    "Alex Mall",
    "ANB Stationers",
    "Aqua Park Shopping Centre",
    "Atlas Mall",
    "Atlas Road Banking Centre Boksburg",
    "Atteridge Plaza",
    "Banbury Cross Village",
    "Batho Plaza",
    "Bedworth Centre",
    "Bella Ombre Shopping Centre",
    "Birchleigh Noth Mall",
    "Blu Valley Mall",
    "Blueberry Square",
    "Boskruin Village Shopping Centre",
    "Boxer Alexandra",
    "BP M2 Motorway & Pick n Pay Express",
    "Brackenhurst Square",
    "Brand Filling Station",
    "Brentwood Park Mall",
    "Broadacres Shopping Centre",
    "Brooklyn Mall",
    "Build It Marapyane ",
    "Caltex Cedar Road Freshstop",
    "Caltex Centre Court",
    "Caltex Redhill freshstop",
    "Caltex Wapadrand Freshstop",
    "Cambridge Crossing",
    "Carletonville Mall",
    "Carletonville Shopping Centre",
    "Carnival Centre",
    "Celtis Ridge Shopping Centre",
    "Central Square",
    "Centurion Golf Estate (Residents Only)",
    "Checkers Mayville",
    "Chilli Lane",
    "Chris Hani Crossing",
    "Clubview Corner Shopping Centre",
    "Co. Space Midrand",
    "Coachmans Crossing",
    "Comaro Crossing",
    "Cornwall View Shopping Centre",
    "Cosmo Business Park",
    "Cosmo Mall",
    "Cradlestone Mall",
    "Cresta Crossing",
    "Crowthorne Shopping Centre",
    "Dainfern Estate (Residents Only)",
    "Decathlon Alberton",
    "Decathlon Centurion",
    "Decathlon Roodeport",
    "Design Quarter",
    "Dobsonville Mall",
    "Eagle Canyon Golf Estate (Residents Only)",
    "East Point Shopping Centre",
    "Echo Fuel Station",
    "Eden terrace Shopping Centre",
    "Electron Excgange",
    "Elgin mall",
    "Elohim Skryfbehoeftes",
    "Engen 99 Krugersdorp West",
    "Engen Filling Station Azaadville",
    "Ferndale On Republic",
    "Festival Mall",
    "Fin Forum",
    "Firestation Rosebank",
    "Flora Shopping Centre",
    "FNB Bank City",
    "FNB Fairlands",
    "Forest Road Design and Décor",
    "Fourways Crossing",
    "Gezina Galleries",
    "Glen Acres Shopping Centre",
    "Glen Balad Mall",
    "Glenhavie Shell Garage",
    "Gouda Slagtery",
    "Grayston Shopping Centre",
    "Greenstone Shopping Centre",
    "Harding Corner Shopping Centre",
    "Heathway Centre",
    "Highway Vaal Filling Station",
    "Hillfox Value Centre",
    "Inospace-Wynberg Works",
    "Jackal Creek Golf Estate",
    "K90 Centre",
    "Kaalfontein Centre",
    "Kempton Gate Mall",
    "Kempton Shoprite Centre",
    "Killarney Mall",
    "Kolonnade Retail Park",
    "Kopanong Kudube Shopping Centre",
    "Kotwal Motor Spares",
    "KwaMashu Shopping Centre",
    "Kyalami On Main Shopping Centre",
    "L Corro Centre Northcliff",
    "Lavender Square",
    "Mabopene Square",
    "Magalies Village Square",
    "Mall @The Junction",
    "Mall of the South",
    "Mayfield Square Shopping Centre",
    "MBT Filling Station Garsfontein",
    "Meadowdale Mall",
    "Meadowpoint Shopping Centre",
    "Menlyn park Shopping Centre",
    "Midway Mews",
    "Montana Crossing Centre",
    "Morning Glen mall",
    "Morningside Shopping Centre",
    "Nedbank Avo-1",
    "Nedbank Avo-2",
    "North Park Mall",
    "Northlands Corner",
    "Northmead Square",
    "Ntuli Shopping Square",
    "Obarp Tijgervallei",
    "October Avenue Ivory Park",
    "OK Foods Sunnyridge",
    "OK Foods Wadrif",
    "OK Minimark Mossel Bay",
    "Okgonne Filling Station",
    "Olievenhout Plaza",
    "Orange Farm Town Square",
    "Palm court",
    "Park Meadows Mall",
    "Parktown Quarter",
    "Philippolis Hotel",
    "Pick n Pay Centre Sam Sekoti",
    "Piet Els Motors",
    "Pimville Square",
    "Protea point Shopping Centre",
    "Puma Drift",
    "Puma Kabot",
    "Puma Murrayhill",
    "Randburg Square",
    "Randfontein Station Mall",
    "Randridge Mall",
    "Randview Shopping Centre",
    "Raslouw Lifestyle Centre",
    "Redruth Village",
    "Retail Crossing West Rand",
    "River Walk Shopping Centre",
    "Ruimsig Shopping Centre",
    "Rynfield Terrace Shopping Centre",
    "Sam Ntuli Mall",
    "Sannieshof Wholesalers",
    "Sasol Andrew Mapheto",
    "Sasol Bowling Avenue",
    "Sasol Circle Centre",
    "Sasol Cloverdene",
    "Sasol Dalpark",
    "Sasol Davest",
    "Sasol Derdeport",
    "Sasol Diepslot",
    "Sasol Dorandia",
    "Sasol Endenvale",
    "Sasol Excellence",
    "Sasol F & S Nigel",
    "Sasol Hatfield",
    "Sasol Hendrik Potgieter",
    "Sasol Hennopspark",
    "Sasol Hill Street",
    "Sasol Hornsnek",
    "Sasol Houghton",
    "Sasol Jean Avenue",
    "Sasol Kingsview",
    "Sasol Kingsway",
    "Sasol Lynnwood Ridge",
    "Sasol Lyttleton Manor",
    "Sasol Main Reef",
    "Sasol Malanshof",
    "Sasol Mamelodi",
    "Sasol Midrand",
    "Sasol Midridge",
    "Sasol Newmarket",
    "Sasol Nina Park",
    "Sasol Noordheuwel",
    "Sasol North Riding",
    "Sasol Northmead",
    "Sasol Olivedale",
    "Sasol Parkdene",
    "Sasol Philip Nel Park",
    "Sasol Pinehaven",
    "Sasol Ravenwood East",
    "Sasol Ravenwood West",
    "Sasol Rietfontein ",
    "Sasol Risiville",
    "Sasol Roodekruin",
    "Sasol Schurveberg",
    "Sasol Sedibeng",
    "Sasol Skinner Street",
    "Sasol SSS Vanderbijlpark",
    "Sasol St Bernard",
    "Sasol Stormvoel",
    "Sasol Suikerbos Motors",
    "Sasol Thembisa",
    "Sasol Theresa Park",
    "Sasol Van Burren",
    "Sasol Vanderbijlpark",
    "Sasol Vereeniging",
    "Sasol Voortrekker Road",
    "Sasol West Star",
    "Sasol West Village",
    "Sasol Zambezi South",
    "Sebokeng Plaza",
    "Serengeti Golf Estate (Residents Only)",
    "Shell Moreleta Park",
    "Shell Sundowner Motors",
    "Shoprite Centre Marikana",
    "Soshanguve Crossing Mall",
    "Southview Shopping Centre",
    "Soweto Power Park",
    "Spar Boksburg",
    "Springs Mall",
    "Springsgate Shopping Centre",
    "Stonehill Crossing",
    "Strubenvale Pharmacy",
    "Struisbaai Hengel Winkel",
    "Sunagte Farms",
    "Sunninghill Square",
    "Supa Quick Armadale",
    "Supa Quick Germiston ",
    "Supa Quick Lenasia",
    "Talent Demo 1",
    "Talent Test2",
    "The Conservatory @Lakefield",
    "The Courier Guy Alberton",
    "The Courier Guy Bedfordview",
    "The Courier Guy Boksburg",
    "The Courier Guy Broadacres",
    "The Courier Guy Bryanston",
    "The Courier Guy Cape Town Kiosk",
    "The Courier Guy Carletonville",
    "The Courier Guy Cloverdene",
    "The Courier Guy Craighall Park",
    "The Courier Guy Crown Mines",
    "The Courier Guy Dainfern",
    "The Courier Guy Equestria",
    "The Courier Guy Hatfield",
    "The Courier Guy Hennopspark",
    "The Courier Guy Jewel City",
    "The Courier Guy Johannesburg kiosk",
    "The Courier Guy Krugersdorp",
    "The Courier Guy Louis Trichardt",
    "The Courier Guy Midrand",
    "The Courier Guy Northmead",
    "The Courier Guy Parkhurst",
    "The Courier Guy Parys",
    "The Courier Guy Randfontein",
    "The Courier Guy Rivonia",
    "The Courier Guy Silverton",
    "The Courier Guy Springs",
    "The Courier Guy Strydompark",
    "The Courier Guy Vanderbijlpark",
    "The Courier Guy Vareenigning",
    "The Courier Guy Waltevredenpark",
    "The Marc",
    "The Ridge Shopping Centre",
    "The Square",
    "The Village Mall",
    "The Wall Centre Ballito",
    "Thorntree Shopping Centre",
    "To Dye For",
    "Total De Deur",
    "Town Square Mall",
    "Tsakane Corner",
    "Tsakane Mall",
    "TWK Ixopo",
    "TWK Lothair",
    "Verdi Shopping Centre",
    "Victory Park Shopping Centre",
    "Viva CJ Mahomed",
    "VR Mall Edenvale",
    "Warranty House",
    "Waterglen Shopping Centre",
    "Westwood Village",
    "Willow Way Shopping Centre",
    "Willowrock Value Centre",
    "Willows Crossing Centre",
    "Wilrogate Shopping Centre",
    "Wonderpark Shopping Centre",
    "Woodmead Retail Park",
    "Woodmead Super Value Mal",
  ],
  "KwaZulu-Natal": [
    "Aheers Foodworks",
    "Aheers Supermarket",
    "Belele Motors",
    "Berea Centre",
    "Bluff Towers",
    "BP Quarry",
    "Build Hlabisa",
    "Build It Estcourt",
    "Caltex Cato Ridge Freshstop",
    "Caltex Pongola",
    "Caltex Thongasi Freshstop",
    "Caltex Umtentweni",
    "Caltex Winston Park Freshstop",
    "Cedarwood Village Shopping Centre",
    "Checkstar Durban",
    "Checkstar Mount Edgecombe",
    "Checkstar Overport",
    "Colenso Motors",
    "Davenport Square",
    "Delcairn Lifestyle Centre",
    "Die Opstal Memel",
    "Emprint Empangeni",
    "Engen Kenfield",
    "Fairways On Main",
    "Gillitts Corner",
    "Gremlins Margate",
    "Hammarsdale Junction Mall",
    "Heyfields Mall",
    "Hibberdene Super Spar",
    "Hillary Service Station",
    "Jeffs Service Station",
    "Jozini Mall",
    "Kensington Boulevard ",
    "Kozi Café",
    "Lennoxton Service Station",
    "Lusiki Plaza",
    "Mandeni Mall",
    "Matatiele Service Station",
    "Mays Auto Centre",
    "Meerensee Filling Station",
    "Mica Paulpietersburg",
    "Montclair Mall",
    "Mount Edgecombe estate (Residents Only)",
    "Mpophomeni Mall",
    "Musgrave Centre",
    "New Hanover Garage",
    "Newcastle Corner",
    "Nquthu Plaza",
    "OK Express Puma Dalton",
    "Park Boulevard",
    "Phoenix Plaza",
    "Pine Crest Shopping Centre",
    "Post Script Pennington",
    "Protea Hardware Dannhauser",
    "Qualbert Centre",
    "Roservior Hills Shopping Centre",
    "Richmond Shopping Centre",
    "Sasol Bellair",
    "Sasol Maathula",
    "Sasol Merrivale",
    "Sasol NMR",
    "Sasol Port Shepstone",
    "Sasol Salt Rock",
    "Sasol Umgeni",
    "Scottburgh Mall",
    "Scottburgh Motors",
    "Seadoone service Station",
    "South Coast Mall",
    "Southport Swop Shop",
    "Spar 1000 Hills ",
    "Spar Ladysmith",
    "Spar Louwsburg",
    "Spar Mapumulo",
    "Spar Mtunzini",
    "Spar Renckens",
    "Spar Umkomaas",
    "Spar Winterton",
    "Spares City Ulundi",
    "Spargs Supermarket Kokstad",
    "Spargs Superspar Mount Frere",
    "Supa Quick Bergville",
    "Supa Quick Camperdown",
    "Superkhulu Hardware",
    "The Atrium Berea",
    "The Atrium Eshowe",
    "The Courier Guy Ballito",
    "The Courier Guy Dundee",
    "The Courier Guy Empangeni",
    "The Courier Guy Estcourt",
    "The Courier Guy Hillcrest",
    "The Courier Guy Howick",
    "The Courier Guy Kokstad",
    "The Courier Guy Ladysmith",
    "The Courier Guy Manguzi",
    "The Courier Guy Mtubatuba",
    "The Courier Guy Newcastle",
    "The Courier Guy Pietermaritzburg",
    "The Courier Guy Pongola",
    "The Courier Guy Port Edward",
    "The Courier Guy Port Shepstone",
    "The Courier Guy Richards Bay",
    "The Courier Guy Stanger",
    "The Courier Guy Underberg",
    "The Courier Guy Vryheid",
    "Theku Plaza",
    "Tiffany’s Shopping Centre",
    "Total Ashburton",
    "Total Southport",
    "Tugela Ferry Mall",
    "Tugela Truck Inn",
    "TWK Mooi River",
    "TWK Swartberg",
    "TWK Underberg",
    "Umlazi Mega City",
    "Umzimkhulu Mall",
    "Weenen Agri",
    "Westville Junction",
    "Westwood Mall",
    "Zinkwazi Beach Café",
  ],
  Limpopo: [
    "7 Eleven Polokwane",
    "AI 3 Plaasmark",
    "Algemeen Handelaar Maasstroom",
    "Bela Mall",
    "Blouberg Mall",
    "Boabab Wholesaler",
    "Bougainvilla Country Store",
    "Boxer Centre Tzaneen",
    "Build It Maake",
    "Build It Modjadji",
    "Build It Namakgale",
    "Build It Nkwowankowa",
    "Build It Nokaweng",
    "Build It Sekororo",
    "Build It Selala",
    "Bulgerivier Handelaar",
    "Caltex CLB Garage",
    "Cashbuild Seshego",
    "Circle Centre",
    "Driehoek Filling Station",
    "Elegant Fuel Levubu",
    "Enco Filling Station",
    "Game Groblersdal",
    "Goodluck Supermarket",
    "Gravelotte Butchery",
    "Hubyeni Shopping Centre",
    "Jane Furse Plaza",
    "Lephalale Mall",
    "Lorein Supermarket Dwaalboom",
    "Maake Plaza",
    "Mahlakung Plaza",
    "Makhado Air Force Base",
    "Mala Plaza",
    "Mall of the North",
    "Marapong Shopping Centre",
    "Marula Mall ",
    "Masingita Plaza",
    "Modi Mall",
    "Mooketsi Hardware",
    "Moratiwa Crossing",
    "Musina Mall",
    "Nzelele Valley Shopping Centre",
    "Obaro Koedoeskop",
    "Obaro Naboomspruit",
    "Obaro Northam",
    "Obaro Potgietersrus",
    "OK Minimark gigi",
    "OK Minimark Letsitele",
    "OK Minimark Tarentaalrand",
    "Olifant Oasis",
    "Polokwane Cycad Centre",
    "Rooiberg One Stop",
    "Saselamani NKuna Complex",
    "Sasol Peinna Park",
    "Sasol Steelpoort",
    "Sasol Tzaneen",
    "Savemor Diphagane ",
    "Shoprite Mankweng",
    "Sign Centre",
    "Spar Lulekani",
    "Steenbok Handelaars",
    "Supa Quick Polokwane",
    "Superspar plaza Mokopane",
    "Sydney Halt",
    "Thaba Mall",
    "Thavhani Mall",
    "The Courier Guy Bela-Bela",
    "The Courier Guy Groblersdal",
    "The Courier Guy Hoedspruit",
    "The Courier Guy Lephalale",
    "The Courier Guy Modimolle",
    "The Courier Guy Musina",
    "The Courier Guy Phalaborwa",
    "The Courier Guy Polokwane",
    "The Courier Guy Thabazimbi",
    "The Courier Guy Thohoyandou",
    "The Courier Guy Tzaneen",
    "The Eatery on Rissik",
    "Total Masorini Phalaborwa",
    "Tshilamba Retail Centre",
    "Viva Bakenburg",
    "Viva Bandelierkop",
    "Viva Boyne",
    "Viva Dzanani",
    "Viva Marbel Hall",
    "Viva Marholeni",
    "Viva Marken",
    "Viva Ndlwana",
    "Viva Roedtan",
    "Viva Samey",
    "Viva Sibasa",
    "Vivo Savemor",
    "Waterpoort Winke",
  ],
  Mpumalanga: [
    "Amersfoort Filling Station",
    "Blinkwater Vulstasie",
    "Bosbok Apteek",
    "Breyten Hardware",
    "Build It Ayobs",
    "Build It Driefontein",
    "Build It Praktiseer",
    "Build It Tubatse",
    "Caltex Andrew motors",
    "Caltex Bushbuckridge",
    "Caltex Carolina",
    "Caltex Doornkraal",
    "Caltex Forever Resort Badplaas",
    "Caltex Pullenshope",
    "Caltex Superstop Sabie",
    "Caltex White River",
    "Chothia & Corp",
    "Cosmo Centre",
    "Crossing Centre Nelspruit",
    "Crossroads Plaza",
    "Del Judor Mall",
    "Dendars Hardware",
    "Empoyeni Mall",
    "Game Ermelo",
    "Impala Motors",
    "Jumbo Furniture",
    "Kabokweni Plaza",
    "KG Mall",
    "Kwagga Plaza",
    "Londolozi Filling Station",
    "M and J Bottlestore",
    "Malelane Choppies Centre",
    "Marlothi Shopping Centre",
    "Mascor Komatipoort",
    "Masterhoster",
    "MBT Charl Cilliers",
    "MBT Dullstroom",
    "Mica Volksrut",
    "Middleburg Mall",
    "Moollas Hardware",
    "Msogwaba Motors",
    "National Park Butchery",
    "Nelspruit Plaza",
    "Obara Lydenburg",
    "OK Express Machadodorp",
    "OK Foods Middleburg",
    "Orchards N4 Service Station",
    "Pack n Pay Supermarket",
    "Perfect Water Kriel",
    "Phola Mall",
    "Sasol Delmas",
    "Sasol Evander",
    "Sasol Flora Park",
    "Sasol Secunda CBD",
    "Sasol Secunda Junxion",
    "Sasol Sheritas",
    "Sasol Swartbos",
    "Sasol Watermeyer",
    "Sasol West End",
    "Savemor Platsak",
    "Sheba Motors",
    "Spar Belfast",
    "Spar Carolina",
    "Sasol Graskop",
    "Spar Savemor Arnot",
    "Starstop Machado",
    "Steyns Motors",
    "Task Motors Barberton",
    "The Courier Guy Barberton",
    "The Courier Guy Bethal",
    "The Courier Guy Burgersfort",
    "The Courier Guy Ermelo",
    "The Courier Guy Komatipoort",
    "The Courier Guy Lydenburg",
    "The Courier Guy Malelane",
    "The Courier Guy Middelburg",
    "The Courier Guy Nelspruit",
    "The Courier Guy Piet Retief",
    "The Courier Guy Secunda",
    "The Courier Guy Standerton",
    "The Courier Guy Volksrust",
    "The Courier Guy Witbank",
    "Tops Ogies",
    "Village Shopping Centre",
    "Viva Big 5 Nelspruit",
    "White River Crossing",
    "White River Squar",
  ],
  "Northern Cape": [
    "Alstop Supermarket",
    "Auto Tyre Barkly West",
    "Carnarvon Supermarket",
    "Die Bondeltjie",
    "Dop en Kreef",
    "Grootdrink Winkel & Drankwinkel",
    "Hoofweg Motors",
    "KBD Engen Fuel Station",
    "Kenhardt Fuel Station",
    "Keurstop Diensstasie",
    "Kim Park Shopping Centre",
    "Klein Oqis",
    "Kuruman Mall",
    "KVB Vosburg",
    "Leka Liqours",
    "Lime Acres Slaghuis",
    "Loxton Lekker",
    "Marydale Garage",
    "Mollies Vulstasie",
    "Mouers Enterprise",
    "N12 Total Strydenburg",
    "Oasis Café Noupoort",
    "Obaro Hartswater",
    "OK Foods Calvinia",
    "OK Foods Garies",
    "OK Foods Rednic",
    "OK Foods Sutherland",
    "OK Grocer Black Rock",
    "OK Grocer Hopetown",
    "OK Grocer Hotazel",
    "OK Minimark Olifantshoek",
    "OK Minimark Towers",
    "Ons Apteek Aggeneys",
    "Onse Winkel Baken",
    "OVK Colesburg",
    "OVK Hopetown",
    "OVK Petrusville",
    "OVK Prieska",
    "Pitstop Biltong & Tuckshop",
    "Pofadder Auto",
    "Print @Victoria West",
    "Redira Clothing Augrabies",
    "Redira Clothing Upington",
    "Roux Drankwinkel",
    "Sasol Tsantsabane",
    "Savemor Hanover",
    "Savemor Nieuwoudtville",
    "Saverite Douglas",
    "Saverite Kakamas",
    "Saverite Keimoes",
    "Saverite Stella",
    "Saverite Warrenton",
    "Spar Danielskuil",
    "Spar Loeriesfontein",
    "Spar Port Nolloth",
    "Spar Prieska",
    "The Courier Guy Colesburg",
    "The Courier Guy De Aar",
    "The Courier Guy Douglas",
    "The Courier Guy Hopetown",
    "The Courier Guy Kathu",
    "The Courier Guy Kimberley",
    "The Courier Guy Kimberley 2",
    "The Courier Guy Kuruman",
    "The Courier Guy Prieska",
    "The Courier Guy Springbok",
    "The Courier Guy Upington",
    "Total Fraserburg",
    "Vaalbos Hardware",
    "VDK Two Way Radios ",
    "Viva Kagung",
    "Werda Supermark Phillipstown",
    "Williston Vleiskooperasi",
  ],
  "North West": [
    "Boitekong Mall",
    "Boshoek Supermarket",
    "Caltex Tuang",
    "Damdoryn Pharmacy",
    "Derby Fuel and Truck",
    "Emslies Engen",
    "Exel-Mams Truck Inn",
    "Flamwood Walk",
    "Foodzone Rietfontein",
    "Gopane Filling Station",
    "Kanana Mall",
    "Louwna Supermark",
    "Magalies View",
    "MBT N14 Ventersdorp",
    "Mogwase Hardware",
    "Obaro Brits",
    "Obaro Potchefstroom",
    "Obaro Schuinsdrift",
    "OK Foods Coligny",
    "OK Foods La Hoff",
    "Ottosdal Pharmacy",
    "Panorama Kwikspar",
    "Puma Bothaville",
    "Puma Bultfontein",
    "Puma Ganyesa",
    "Puma Watsonia",
    "Quattro Fuels",
    "Reivilo Petroleum",
    "Rietvlei Melkery & Slaghuis",
    "Rousseau Vulstasie",
    "Rustenburg Mall",
    "Sasol Aerodrome",
    "Sasol Baillie Park",
    "Sasol Brits 1",
    "Sasol Broederstroom",
    "Sasol Goudkop",
    "Sasol Inn",
    "Sasol Mafikeng",
    "Sasol Protea Park",
    "Sasol Riviera Park",
    "Saverite Hartbessfontein",
    "Scott Crescent Spar",
    "Spar Delareyville",
    "Stellaronas Carwash",
    "Subway Motors",
    "The Courier Guy Bloemhof",
    "The Courier Guy Klerksdorp",
    "The Courier Guy Lichtenburg",
    "The Courier Guy Mafikeng",
    "The Courier Guy Potchefstroom",
    "The Courier Guy Rustenburg",
    "The Courier GuyVryburg",
    "The Courier Guy Zeerust",
    "Total Hekpoort",
    "Total Meiringspark",
    "Total Orkney",
    "Total Skeerpoort",
    "Tower Mall",
    "Truck Inn Potchefstroom",
    "Vaalkop Tuckshop",
    "Viva Slurry",
    "Vrugte uit die Boord",
    "Waterfall Mall",
    "Zeerust Shopping Centr",
  ],
  "Western Cape": [
    "30 Voortrekker Road",
    "ABC Boekwinkel",
    "Ashton Platform 62",
    "ATKV Hartenbos Standoord",
    "Atlantis Office Park",
    "Avanti office Park",
    "Bayview Centre",
    "Baywest Mall",
    "Caltex Dana Bay",
    "Car Motors Clanwilliam",
    "Central Ceres Motors ",
    "Central Garage Gansbaai",
    "Cycleworx Sedgefield ",
    "De Kraal Slaghuis Brandvlei",
    "Drummong Arms Restaurant ",
    "Eden on the Bay",
    "Emporium Centre",
    "Evita se Perron",
    "Fish Hoek Town Square",
    "Garden Route Meat Market",
    "Gardens Shopping Centre",
    "Gugulethu Square",
    "HD Ruiters Padkafee",
    "Inospace – Epping Works",
    "Inospace – Powder Mill",
    "Inospace - Textile Exchange",
    "Inospace – The Island",
    "Inospace – Wetton Works",
    "Knysna Mall",
    "Kouestroom Bouers",
    "KVB Murraysburg",
    "La Belle Q4 Stikland",
    "Laborie Centre",
    "Lamberts Bay Signs and Printing",
    "Langemeer Service Station",
    "Lansdowne Corner",
    "Macassar Shopping Centre",
    "Maynard Mall",
    "Mcgregor Drankwinkel",
    "Megasave Lutzville",
    "Meltz Centre",
    "Merweville Mall",
    "Midway Centre",
    "Midway Express Breede Rivier",
    "Moov Riviersonderend Country Store",
    "N1 City Mall",
    "Namaqua Garage Vanryhnsdorp",
    "Neelsie Student Centre",
    "Nella se Winkel",
    "Noble Park Shopping Centre",
    "Nuveld Motors",
    "Nyanga Junction",
    "OK Foods Laingsburg",
    "OK Foods Velddrif",
    "OK Foods Villiersdorp",
    "OK Greyton",
    "OK Grocer Barrydale",
    "OK Minimark Ceres",
    "OK Minimark Mowbray",
    "OK Minipark Napier",
    "OK Minimark Onrus",
    "OK Minimark Strandfontein",
    "OK Minimark Wolseley",
    "On Darwin Shopping Centre",
    "Ottery Value Centre",
    "Oudtshoorn Ford",
    "Palm Tyres",
    "Pearly Beach Shop",
    "Pelican Park Shopping Centre",
    "Piazza da Luz",
    "Pick n Pay Riebeeck Wes",
    "Pinehurst Shopping Centre",
    "Piquetberg Mall",
    "Pollocks Pizza Café",
    "Pringle Bay Mini Market",
    "Print @Groot Brakrivier",
    "Q Square Shopping Centre",
    "Rambrandt Mall",
    "Royal Herold",
    "Royal Uniondale",
    "Sasol Buffelsfontein",
    "Sasol De Bron",
    "Sasol Erica Road",
    "Sasol George Highway",
    "Sasol Kleinmond",
    "Sasol Melkbosstrand",
    "Sasol Parklands",
    "Sasol Roelf & Jacks",
    "Sasol Somerset West",
    "Sentra De Rust",
    "Shell Albertinia",
    "Shell Boulevard",
    "Shell Steenberg",
    "Shell Suiderhof Motors",
    "Silo Exchange",
    "Spar Belmont",
    "Spar Bonnievale",
    "Spar Calitzdorp",
    "Spar de Doorns",
    "Spar Hopefield",
    "Spar Ladismith",
    "Spar Langebaan",
    "Spar Moorreesburg",
    "Spar Porterville",
    "Spar Prince Albert",
    "Spar Saldanha",
    "Spar St Helena Bay",
    "Spar Yzerfontein",
    "Stanford General Dealer",
    "Stellenbosch Square",
    "Supa Quick Caledon",
    "TCG Cape Town Depot",
    "The Cabin Restaurant & Pub",
    "The Courier Guy Beaufort West",
    "The Courier Guy Bellville",
    "The Courier Guy Brackenfell",
    "The Courier Guy Bredasdorp",
    "The Courier Guy Ceres",
    "The Courier Guy Durbanville",
    "The Courier Guy Fish Hoek",
    "The Courier Guy Franschhoek",
    "The Courier Guy George",
    "The Courier Guy Grabouw",
    "The Courier Guy Heidelberg (Cape)",
    "The Courier Guy Hermanus",
    "The Courier Guy Hout Bay",
    "The Courier Guy Khayelitsha",
    "The Courier Guy Knysna",
    "The Courier Guy Malmesbury",
    "The Courier Guy Mokopane",
    "The Courier Guy Montague Gardens",
    "The Courier Guy Mossel Bay",
    "The Courier Guy Muizenberg",
    "The Courier Guy Ottery",
    "The Courier Guy Oudtshoom",
    "The Courier Guy Paarl",
    "The Courier Guy Parklands",
    "The Courier Guy Piketberg",
    "The Courier Guy Robertson",
    "The Courier Guy Somerset West",
    "The Courier Guy Steinhoff Business Park",
    "The Courier Guy Stellenbosch",
    "The Courier Guy Still Bay",
    "The Courier Guy Swellendam",
    "The Courier Guy Vredenburg",
    "The Courier Guy Vredendal",
    "The Courier Guy Wellington",
    "The Courier Guy Worcester",
    "The Crags Superette",
    "The Deli Rawsonville",
    "The Orchard Farm Stall Grabouw",
    "The Paddocks Shopping Centre",
    "The Pavilion Shopping Centre",
    "The Route 62 Stop",
    "Tulbagh Garage ",
    "Tygerberg Campus",
    "Village Centre Bettys Bay",
    "Viva Elukwatini",
    "Voorbaai Truckport ",
    "Vredenburg Auto",
    "Waves Garage Convenience Store",
    "Werners Meat Market",
    "Weskus Mall",
    "Westgate Mall",
    "Whale Coast Mall",
    "Wilderness Motors",
    "Woodmill Lane Shopping centre",
  ],
};

export const postnet = {
  "Eastern Cape": [
    "Beacon Bay	",
    "Cradock	",
    "Crossways ELS	",
    "Gonubie	",
    "Graaff	",
    "Grahamstown	",
    "Greenacres	",
    "Hunters Retreat	",
    "Jeffreys Bay	",
    "King Williams Town	",
    "Metlife Plaza	",
    "Moffett on Main	",
    "PE Waterfront	",
    "Port Alfred	",
    "Queenstown	",
    "Savoy Mthatha	",
    "Southernwood	",
    "St Francis Bay	",
    "Stirling	",
    "Sunridge Village	",
    "The Acres	",
    "Uitenhage 	",
    "Vincent	",
    "Walmer",
    "Willow Roa",
  ],
  "Free State": [
    "Bloemfontein Langenhoven Park",
    "Bloemfontein Waterfront",
    "Fleurdal",
    "Frankfort",
    "Goldfields",
    "Heilbron",
    "Kroonnstad",
    "Langenhoven Park",
    "Northridge Mall",
    "Parys",
    "Preller (Bloemfontein)",
    "Welko",
  ],
  Gauteng: [
    "Alberton",
    "Allens Nek",
    "Arcon Park",
    "Atterbury",
    "Balfour Park",
    "Bassonia",
    "Bedford Centre",
    "Bedfordview",
    "Bedworth Park",
    "Benoni Lakeside",
    "Birchleigh",
    "Blue Hills",
    "Blueberry",
    "Boksburg Centre Point",
    "Boskruin Village",
    "Braamfontein",
    "Bracken City",
    "Brakpan",
    "Bram Fischer",
    "Brentwood Park",
    "Brits",
    "Brixton",
    "Broadacres",
    "Brooklyn",
    "Brooklyn SAQA",
    "Bruma",
    "Bryanston",
    "Castle Walk",
    "Cornwall View",
    "Cosmo City",
    "Craighall",
    "Cresta",
    "Crowthorne",
    "Dainfern Square",
    "Derdepark",
    "Doornpoort",
    "DoringKloof",
    "Dowerglen",
    "East Lynne",
    "East Rand Corner",
    "Eastwood Village",
    "Eden Glen",
    "Edenvale",
    "EI Ridge",
    "Elarduspark",
    "Eldo Square",
    "Eldoraigne",
    "Epsom Downs",
    "Equestria",
    "Esselen Street",
    "Faerie Glen",
    "Fairlands",
    "Farrarmere",
    "Feather Square",
    "Featherbrooke Village",
    "Fendale on Republic",
    "Ferndale Village",
    "Florida",
    "Fontainbleau",
    "Fordsburg",
    "Forest Hill",
    "Fourways Crossing",
    "Fourways Mall",
    "Gallo Manor",
    "Gezina",
    "Gift Acres",
    "Glen Marias",
    "Glenfair",
    "Glenhazel",
    "Greenside",
    "Grey Owl",
    "Groenkloof",
    "Hartbeespoort Dam",
    "Hatfield ",
    "Heidelberg",
    "Heidelberg Mall",
    "Hennopspark",
    "Hyde Park Corner",
    "Irene",
    "Jackal Creek Corner",
    "Jewel City",
    "JHB CBD Fox Street",
    "Kempton Gate",
    "Kempton Park",
    "Killerney Mall",
    "Kolonnade",
    "Krugersdorp",
    "Kya Sand",
    "Kyalami",
    "Lambton",
    "Laudium",
    "Lemon Tree",
    "Lenasia",
    "Linden",
    "Linksfield (Neighborhood Square)",
    "Loftus Park",
    "Lynnwood Hillcrest",
    "Lynnwood Lane",
    "Lyttelton",
    "Mall of the South",
    "Mayville",
    "Meadowdale",
    "Melrose Arch",
    "Meville",
    "Menlo Park",
    "Menlyn (Waterkloof Glen)",
    "Meyersdale",
    "Meyerton",
    "Midrand",
    "Midstream",
    "Montana",
    "Monument Park",
    "Mooikloof",
    "Morningside",
    "Mulbarton",
    "N1 Big Bird",
    "Newtown Junction",
    "Nicolway",
    "Nigel",
    "Noordheuwel",
    "Northcliff",
    "Northcliff Square",
    "Northgate",
    "Northworld",
    "Norwood",
    "Oakfields",
    "Oaklands",
    "Old JHB Road (Lifestyle Centre)",
    "Olivdale",
    "Olivewood",
    "Ontdekkers",
    "Ormonde",
    "Palm Court",
    "Parkhurst",
    "Parkrand",
    "Parktown",
    "Parkview",
    "Paulshof",
    "Pierre Van Ryneveld",
    "PostNet-Linden",
    "PostNet Watermeyer Park",
    "Pretoria CBD",
    "Pretoria North (Nina Park)",
    "Pretoria The Grove",
    "Pretoria West",
    "Princess Crossing",
    "Queens Corner",
    "Radiokop",
    "Rand Steam",
    "Randburg CBD",
    "Randfontein",
    "Rant En Dal",
    "Raslouw",
    "Ridgeway Gardens",
    "Rivonia",
    "Rosebank",
    "Ruimsig Centre",
    "Rustenburg Square",
    "Rynfield Terrace",
    "Sandton City",
    "Sasolburg",
    "Saxonworld",
    "Serengeti",
    "Silver Lakes",
    "Silverton",
    "Sinoville",
    "South East Boulevard",
    "Southdale",
    "Southdowns",
    "Springs Mall",
    "Springsgate",
    "Station Square",
    "Stoneridge",
    "Strubens Valley",
    "Summerfields",
    "Sunninghill",
    "Sunninghill Chilli Lane",
    "Sunward Lifestyle Centre",
    "The Glen",
    "The Islands",
    "The Reef",
    "Three Rivers",
    "Town Midrand",
    "Trinity Village",
    "Vaal Mall",
    "Vaal Park",
    "Van Der Hoff",
    "Verwoerd Park",
    "Victory Park",
    "Vorna Valley",
    "Walkerville",
    "Waterfall Corner",
    "Waterfall Mall",
    "Waterfall Ridge",
    "Waterkloof Ridge",
    "Waverley",
    "Westgate",
    "Westwood Village ",
    "Wonderboom Junction",
    "Woodmea",
  ],
  "KwaZulu-Natal": [
    "Amanzimtoti",
    "Ballito",
    "Berea Road",
    "Bluff",
    "Chatsworth",
    "Cowey Park",
    "Dundee",
    "Durban Club Chambers (DBN CBD)",
    "Empangeni",
    "Estcourt",
    "Glen Ashley",
    "Glenwood",
    "Hillcrest",
    "Hilton",
    "Howick ",
    "Kloof",
    "Knowles Centre",
    "La Lucia",
    "Linkhills Waterfall",
    "Margate",
    "Matatiele",
    "Mount Edgecombe",
    "Mtubatuba",
    "Newcastle Mall",
    "Nottingham Road",
    "Pavilion",
    "Pietermaritzburg Athlone",
    "Pietermaritzburg Hayfields",
    "Pietermaritzburg ",
    "Pinetown",
    "Pongola",
    "Port Edward",
    "Port Shepstone",
    "Queensburg",
    "Richards Bay",
    "Rolyats",
    "Salt Rock",
    "Samia",
    "Scottburg",
    "Shelly Beach",
    "South Beach",
    "Sparks Road",
    "Stanger",
    "Umdloti",
    "Umhlanga Ridge",
    "Umhlanga Village",
    "Verulam",
    "Victoria Square",
    "Vryheid",
    "Westville",
    "Westville North",
    "Windermere",
    "Winterton",
  ],
  Limpopo: [
    "Flora Park",
    "Giyani",
    "Hampton Court",
    "Ivy Park",
    "Lephalale (Ellisras)",
    "Library Gardens",
    "Maake Plaza",
    "Makhado (Louis Trichard)",
    "Mall of the North",
    "Modjadji Plaza",
    "Mokopane",
    "Musina",
    "Naboomspruit",
    "Paledi Mall",
    "Petrostop Polokwane",
    "Polokwane North",
    "Thavhani Mall",
    "Thohoyandou",
  ],
  Mpumalanga: [
    "Ben Fleur",
    "Bronkhorstspruit",
    "Burgersfort",
    "Delmas",
    "Ermelo Express",
    "Hazyview",
    "Highveld Mall",
    "Hoedspruit",
    "Kriel",
    "Lydenburg",
    "Malalane",
    "Middelburg Aerorand",
    "Nelspruit Crossing",
    "Nelspruit The Grove",
    "Phalaborwa",
    "Piet Retief",
    "Steelpoort",
    "Trichardt",
    "Whiteriver Crossing",
    "Witbank",
  ],
  "Northern Cape": [
    "Hartswater",
    "Kathu Heritage Square",
    "Kathu Village Mall",
    "Kimberley",
    "Kuruman",
    "Postmasburg",
    "Upington",
    "Vredendal",
    "Vryburg",
  ],
  "North West": [
    "Bela Bela",
    "Hammanskraal",
    "Marbel Hall",
    "Mooinooi",
    "PostNet Groblersdal",
    "Thabazimbi",
  ],
  "Western Cape": [
    "Bellville Edward Street",
    "Brackenfell",
    "Bredasdorp",
    "Burgundry Estate",
    "Canal Walk",
    "Cape Gate (New)",
    "Cape Town Cape Quarter",
    "Cape Town Gardens",
    "Cape Town Metropolitan",
    "Century City",
    "Claremount",
    "Constantia",
    "CPT Lakeside",
    "Durbansville",
    "Fish Hoek",
    "Franschhoek",
    "Gansbaai",
    "Gardens Shopping Centre",
    "George",
    "Gordon’s Bay",
    "Groot Brak",
    "Haasendal",
    "Hartenbos",
    "Heather Park",
    "Hermanus",
    "Hermanus Sandbaai",
    "High Str Tygervalley",
    "Hout Bay",
    "Kenilworth",
    "Knysna",
    "Kiulsriver",
    "Langebaan",
    "Malmesbury",
    "Meadowridge",
    "Melkbosstrand",
    "Milnerton",
    "Mossel Bay",
    "N1 Value Centre",
    "Observatory",
    "Oudtshoorn",
    "Paarl",
    "Paddocks",
    "Parow",
    "Pinelands",
    "Plattekloof",
    "Plattner Blvd",
    "Plattenberg Bay",
    "Plumstead",
    "Riversdal",
    "Robertson",
    "Rondebosch",
    "Sedgefield",
    "Somerset Mall",
    "Somerset West",
    "Steenberg Village",
    "Stellenbosch Eikestad",
    "Stilbaai",
    "Strand",
    "Sun Valley",
    "Table View Flamingo Sqaure",
    "Table View Parklands",
    "Table View Sandown",
    "Three Anchor Bay",
    "Tokai",
    "V & A Waterfront",
    "West Coast Village ",
    "Woodstock ",
    "Worcester",
  ],
};
