export const states = {
  Nigeria: [
    "Abuja(fct)",
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
  ],
  SouthAfrican: [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "Northern Cape",
    "North West",
    "Western Cape",
  ],
};

export const banks = {
  Nigeria: [
    "Access Bank",
    "Zenith Bank",
    "GTBank",
    "First Bank of Nigeria",
    "UBA",
    "Union Bank",
    "Fidelity Bank",
    "FCMB",
    "Citibank Nigeria",
    "Ecobank",
    "Heritage Bank",
    "Keystone Bank",
    "Standbic IBTC",
    "Standard Chartered",
    "Sterling Bank",
    "Unity Bank",
    "Wema Bank",
  ],
  SouthAfrica: [
    " Absa Bank",
    " African Bank",
    " Bidvest Bank",
    " Capitec Bank",
    " Discovery Bank",
    " First National Bank",
    " Investec",
    " Nedbank",
    " Standard Bank",
    " Ubank",
    " TymeBank",
  ],
};
